[project]
name = "oaqjp-final-project-emb-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "pylint>=4.0.4",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]
